ARG  BASE_IMAGE_TAG=7.4-cli-2.x
FROM drupaldocker/php:${BASE_IMAGE_TAG}

# Create directories for Drupal
RUN mkdir -p /tmp/drupal && chown www-data:www-data /tmp/drupal
RUN chown www-data:www-data /var/www
WORKDIR /var/www/drupal

# Config
ENV DOCROOT=/var/www/drupal/web
#ADD apache.conf /etc/apache2/sites-enabled/000-default.conf
ADD bashrc.sh /var/www/.bashrc
ADD drushrc.php /etc/drush/drushrc.php
